#
# This source file is part of the Stanford Biodesign Digital Health RadGPT open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

dirs:
  - .
useGitIgnore: true
ignorePatterns:
  - pattern: '^doc:.*$'
  - pattern: '^http://localhost.*$'
  - pattern: '^https://.*openai\.com'