//
// This source file is part of the Stanford Biodesign Digital Health RadGPT open-source project
//
// SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT
//

/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedpageImport } from './routes/protected_page'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProtectedpageRoute = ProtectedpageImport.update({
  path: '/protected_page',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/protected_page': {
      id: '/protected_page'
      path: '/protected_page'
      fullPath: '/protected_page'
      preLoaderRoute: typeof ProtectedpageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/protected_page': typeof ProtectedpageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/protected_page': typeof ProtectedpageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/protected_page': typeof ProtectedpageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/protected_page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/protected_page'
  id: '__root__' | '/' | '/protected_page'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedpageRoute: typeof ProtectedpageRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedpageRoute: ProtectedpageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/protected_page"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/protected_page": {
      "filePath": "protected_page.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
