#
# This source file is part of the Stanford Biodesign Digital Health RadGPT open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test Web

concurrency:
  group: web-build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: ./web

jobs:
  reuseaction:
    name: REUSE Compliance Check
    uses: StanfordBDHG/.github/.github/workflows/reuse.yml@v2
  markdownlinkcheck:
    name: Markdown Link Check
    uses: StanfordBDHG/.github/.github/workflows/markdown-link-check.yml@v2
  eslint:
    name: ESLint
    uses: ./.github/workflows/eslint.yml
    permissions:
      contents: read
      checks: write
    with:
      working-directory: web
  test:
    name: vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Node Dependencies
        run: npm ci
      - name: Run vitest
        working-directory: web
        run: npm run test
  tsc:
    name: TSC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Node Dependencies
        run: npm ci
      - name: Run TSC
        working-directory: web
        run: npm run tsc:ci
