#
# This source file is part of the Stanford Biodesign Digital Health RadGPT open-source project
#
# SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Deployment Firebase

on:
  push:
    branches:
      - main
    paths:
      - firebase/**
  workflow_dispatch:
    inputs:
      environment:
        description: |
          The GitHub deployment environment.
        required: true
        default: "development"
        type: choice
        options:
          - development
          - staging
          - production
  workflow_call:
    inputs:
      environment:
        description: |
          The GitHub deployment environment.
        required: false
        type: string
        default: development

concurrency:
  group: deployment-firebase-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  determineenvironment:
    name: Determine Environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Determine Environment
        id: set-env
        run: |
          if [[ -z "${{ inputs.environment }}" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          else
            echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          fi
  vars:
    name: Inject Environment Variables In Deployment Workflow
    needs: determineenvironment
    runs-on: ubuntu-latest
    environment: ${{ needs.determineenvironment.outputs.environment }}
    outputs:
      FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
    steps:
      - run: |
          echo "Injecting Environment Variables In Deployment Workflow: ${{ vars.FIREBASE_PROJECT_ID }}"
  buildandtest:
    name: Build and Test
    needs: determineenvironment
    uses: ./.github/workflows/build-and-test.firebase.yml
    permissions:
      contents: read
      checks: write
    secrets: inherit
  e2e:
    name: End-to-end Test
    uses: ./.github/workflows/playwright-e2e.yml
    permissions:
      contents: read
      checks: write
    secrets: inherit
  deployfirebase:
    name: Deploy Firebase Project
    needs: [buildandtest, determineenvironment, vars, e2e]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "firebase"
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install Firebase CLI Tools
        run: npm install -g firebase-tools
      - name: Setup Python Virutal Environment
        working-directory: firebase
        run: |
          python3.10 -m venv functions/venv
          . functions/venv/bin/activate
          python3.10 -m pip install -r functions/requirements.txt
      - name: Deploy to Firebase
        working-directory: firebase
        run: |
          echo -n "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 -d > "$RUNNER_TEMP/google-application-credentials.json"
          export GOOGLE_APPLICATION_CREDENTIALS="$RUNNER_TEMP/google-application-credentials.json"
          echo "Stored the Google application credentials at $GOOGLE_APPLICATION_CREDENTIALS"
          firebase deploy --project ${{ needs.vars.outputs.FIREBASE_PROJECT_ID }} --only firestore,storage,functions:on_report_meta_data_delete,functions:on_medical_report_upload,functions:on_detailed_explanation_request,functions:on_annotate_file_retrigger
      - name: Clean up Google application credentials
        if: always()
        run: |
          rm -rf $RUNNER_TEMP/google-application-credentials.json || true
