#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2024 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Playwright Tests

concurrency:
  group: playwright-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: web/package-lock.json
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Install Firebase CLI Tools
        working-directory: web
        run: npm install -g firebase-tools
      - name: Install Playwright Browsers
        working-directory: web/e2e-tests
        run: |
          npm install
          npx playwright install --with-deps
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up Env for Firebase Functions
        working-directory: firebase
        run: |
          cd functions
          echo -n "OPENAI_API_KEY=" > .secret.local
          echo "${{ secrets.OPENAI_API_KEY }}" >> .secret.local
          echo "RADGRAPH_EMULATED=true" >> .secret.local
      - name: Setup Python Firebase Virutal Environment
        working-directory: firebase
        run: |
          python3.10 -m venv functions/venv
          . functions/venv/bin/activate
          python3.10 -m pip install -r functions/requirements.txt
      - name: Setup Python Google Cloud Virutal Environment
        working-directory: radgraph_function
        run: |
          python3.10 -m venv venv
          . venv/bin/activate
          python3.10 -m pip install -r requirements.txt
      - name: Set up Env for Web
        working-directory: web
        run: cp .env.example .env
      - name: Run Playwright tests
        working-directory: firebase
        run: |
          echo -n "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 -d > "$RUNNER_TEMP/google-application-credentials.json"
          export GOOGLE_APPLICATION_CREDENTIALS="$RUNNER_TEMP/google-application-credentials.json"
          echo "Stored the Google application credentials at $GOOGLE_APPLICATION_CREDENTIALS"
          firebase emulators:exec "cd ../web/e2e-tests/ && npx playwright test" --project demo-radgpt
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: web/e2e-tests/test-results/
          retention-days: 30
      - name: Clean up Google application credentials
        if: always()
        run: |
          rm -rf $RUNNER_TEMP/google-application-credentials.json || true
          rm -rf firebase/functions/.secret.local || true
